@startuml
'https://plantuml.com/class-diagram

Appareil <|-- Lampe
Appareil <|-- Hifi
Appareil <-- Telecommande

class Telecommande {


}

class Appareil {

}

class Lampe {

}

class Hifi {

}
@enduml