@startuml
'https://plantuml.com/class-diagram

Appareil <|-- Lampe
Appareil <|-- Hifi
Appareil <|-- CheminAdaptateur
Telecommande "*" --> "*" Appareil: - appareils
CheminAdaptateur "1" --> "1" Cheminee: - cheminee

'''classes
class Telecommande {
    - lampes: ArrayList
    + ajouterAppareil(Lampe)
    + activerAppareil(int)
    + desactiverAppareil(int)
    + activerTout()
    + toString()
}

interface Appareil {
    + allumer()
    + eteindre()
}

class Lampe {
    - nom: String
    - allume: boolean
    + allumer()
    + eteindre()
    + toString()
    + isAllume()
}

class Hifi {
    - son: int
    + allumer()
    + eteindre()
    + toString()
}

class Cheminee {
    - intensite: int
    + changerIntensite()
    + getLumiere()
    + toString()
}

class CheminAdaptateur {

    - Cheminee: cheminee
    + allumer()
    + eteindre()
}
@enduml